# تنظیمات حافظه JVM و بهینه‌سازی دیمن گریدل.
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:+UseStringDeduplication

# فعال‌سازی اجرای موازی تسک‌ها.
org.gradle.parallel=true

# فعال‌سازی دیمن گریدل.
org.gradle.daemon=true

# فعال‌سازی کش پیکربندی.
org.gradle.configuration-cache=true

# فعال‌سازی کش بیلد.
org.gradle.caching=true

# فعال‌سازی مانیتورینگ تغییرات فایل‌های سیستم.
org.gradle.vfs.watch=true

# تنظیم خروجی کنسول.
org.gradle.console=rich

# تنظیم نمایش هشدارها.
org.gradle.warning.mode=all

# فعال‌سازی پکیج‌های نوین AndroidX.
android.useAndroidX=true

# غیرفعال‌سازی Jetifier به دلیل پشتیبانی بومی تمام کتابخانه‌ها از AndroidX.
android.enableJetifier=false

# فعال‌سازی حالت پیشرفته بهینه‌ساز R8.
android.enableR8.fullMode=true

# بهینه‌سازی و حذف منابع بلااستفاده.
android.enableResourceOptimizations=true

# فعال‌سازی کلاس‌های منابع غیرانتقالی (Non-transitive R classes).
android.nonTransitiveRClass=true

# فعال‌سازی شناسه‌های متغیر منابع برای بهبود سرعت کامپایل.
android.nonFinalResIds=true

# تنظیم استایل پیش‌فرض کدهای کاتلین.
kotlin.code.style=official

# فعال‌سازی کامپایل افزایشی کاتلین.
kotlin.incremental=true
kotlin.incremental.android=true

# فعال‌سازی تسک‌های موازی کاتلین.
kotlin.parallel.tasks.in.project=true

# استراتژی اجرای کامپایلر کاتلین.
kotlin.compiler.execution.strategy=in-process

# گزارش‌های متریک کامپایلر کامپوز در صورت نیاز با پارامتر خط فرمان فعال می‌شوند.
# ./gradlew assembleRelease -Pandroid.experimental.enableComposeCompilerMetrics=true

# فعال‌سازی تولید خودکار کلاس BuildConfig.
android.defaults.buildfeatures.buildconfig=true

# فعال‌سازی قابلیت Jetpack Compose در بیلد.
android.defaults.buildfeatures.compose=true

# تنظیم محدودیت زمانی ارتباطات شبکه در فرآیند بیلد.
systemProp.org.gradle.internal.http.connectionTimeout=60000
systemProp.org.gradle.internal.http.socketTimeout=60000

# فعال‌سازی همگام‌سازی موازی در نسخه‌های جدید گریدل.
org.gradle.tooling.parallel=true
